language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: tw95wsdmwWzDmBwC0Kh0VB6v0qGPCaK2RRBgwQn0mGckH90k3osWroQeUviXITvfQzetrTThLyxefY3TX0yqp6v9hU+uLLFwVWjO/JFW+jQnnjqOenxbdH4YESwg3EEnDtgjWEUIiaidvM1dvSPUyVNnatdOoaAcvsUg0gMz2VV5s0WLzHBmaAf8aq4HKnMgybkpMSwntL1rbAkto4FUp/afzs29dGYmhYVy7mCc0MaHPs3ZXU2ipFP6d/v8KVXUgjdkvdKX4KiYlFwCPjK+UhRQGRgXrAe0N4/wJUyEyKJtPpinA60FP6JvZyw9d0/qFq2QLAIv2BMxGu4RQpbM9zB24VXktPNsncbKiBVEXiM0sbQU+DEH7bWmDo9MdSzRVgG7XxaejKRH8rkecuoZjk/dq39EtTEcg8AwuqRJZA2ZiUD0eOXrgKHXm+Yn6sWkOqffBESHxOa0zq0K6c1ZOMtGiti/HevJCvC449bkZdcx8GUfdM+bSIXgnXoZYk37w47+hB02PMAl/EF3zS4mRuS9IY2FMxCQ3flwabiolA7/NZCe6czPNrVSSQ1BeLL6c+QX5azfdunBWz7B5ouKFqqc0C2zCQc0LYl1PEEuwKPpqZJ2UiiZdyAXPE84VrHtz1D9R2nABhV9+veZFoczQv1/FRh3Tdr7SMAze4mDra0=
  app: unai-emery
