language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: AZSVbLpTub37oH/yZgEbHTDYroqoqdiJiVM6BCdVmCmQMNpqCF2ZFIIWIavmFQhnaKDklzFd1rbv2/JpcTZu+YbfEt5o3zDdOI+U/+5Wl90DlRkgm6irKTc0M6rsQet1covn8RcuxbHFuRNvX3eIxcuHGiqJVLSsr/sZD8GSCkI/UBt2iAs9MxpTGnC/P51nt3lardWbxY0PB7p7C2yoC3qoFXzqFLUyFqbxczS1C5T8uDC9xgI0SmoJ5LzD+wMd4FpYwqh9hXQzIte7i3Am3/raPzytXttzRKuyxCQi5vJbyl4l5kzHXVuutPLlQu9QHPSIk47fR9pNvY7MmCDZp29dHc/tJhId9xzYZDBWDXR4z0Su+ns5TrUqpME52JSLaJjPSv3RFz44tduDFf1+K0TzI0IAPZ2wSGRCnRv9JG7iWcC0Qv2Fka5LYo7Aft2XisuUlqr8x+6VxBlN9rAHYQpT88mh5x4pgphGHccOO1wV9APo2d3VqBkQgPmLtDZwWC5Cr/YC19OYDilE/hgGpz4bhDvyfclCyunpz4kMsSqIUJbUT2EvfkJ+fHnW/eW2EU1LaMICvfB9xzY9mn33BmtKBVW9XgO7JDNk87KsU7HQ1rufzbf4OlaVb9ji6cNHUZnHzf6mm+lVf9YRgvQOcCDYZppbTte9eIkxSqb7gO0=
  app: unai-emery
