language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: iydoBz/9H8frfv4klmDGtWobuXIoqw8yN8mjurleoTrVybD8eRm3nb7qaERlk/925IW3Iy57poJlwg3i+vy2kRwhAU9xEWoGUIqbbaSfSh2yQhnUVPu7I75oGHUdTMX60ORQGJ+KgsrEkLZv7T8hnoOSgKpXwHrCBFojgkEAg3z/vqvAawiL1M9hzI7hr80NQ75ZjKwzd8/FoAiF0dCWxviDDThPker34qRxHQ5Er3R7d1fk8l2K3HCdUeDJDn9YF329GnmZuPBE8VFGT9IOWFmm1nmYJrG1X8z6iBd5pRA3k59L5XSgxxqra9TfUA2U1nthBZ51MvzOtU+B4eLWYRh3Uh2aVbHncSYKfKYhE1RedGegglrKnYUOSlB8ApXtj8PcJ6n7eYC2VO843vb7A4gTuF/3Ue86dq7ppl5EpjC7GMhr3EIRp5IjdOgk3NOLlRFDVip9VZvF3wqLb8kmcrNBupqUkyQUkfrDTUuQzrbahY8J3AMyyuiD4sdsYI9Q9iGfnKYtx4nbNHkBkeUtC2pvbW0IL8by7Tkj9mYnnlo2a7ljLDIAPxyO6NqakYwUaRXtFu0gy6+hDLY2sVALsNeGLWuz4cAXmlZyw9Zrl8Zswt5PZuVPcWQdg5flOY9dYGSTCvI+t2HDd2hfjZ4DUpKwirUgZzD7W0S4mDRRgw4=
  app: unai-emery
  on:
    repo: devawal5/BasicWebApp
