language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: WIVwUm6I7poTbgFNCXgXyXtQ+OvUDeXU1G5k25PCtRNY1QYVLIqLp7XKfImPh5vPxmKyp2xVlSMjAgeziLBKyjvxjmZJ3iiQrSd5YIf/iE+eyroOeUklwEMd1W0cnkmYXLmnNIsOx4k84s1NZ2zxonj0AfVbbolw3bzzkPZU5azWcCWiNAwF+o5qoFzffG0H4kudtP4j9LFekUuPXueErPGxnT1IXjt/HCrgqqVTEJCWeZTzj0AvpfTlaYtaTUNT+TwiC14zra5rGStzfzTsq0pcwwc19P0EVFltvOyfd7pwHA9D2a8HyIh8idO5IX/8uoWPk/xBMLMwscL1pLuOo3Ht35iz42Ie/GKBM1J4aGIWmrCpBOrYQiquPFFgQFrRuWHZRMMG+tq+Hx32OI/xZ5X1yyh0qy3cdzxec/psvisWQuR6bfxSjRY04teoBmXAs2NZSoE3Z3RYl72NUxPYP6fjRXVAJt+ZtiVfglBYyCrOHDWpnWgud6OJ9unjHaTkTUhG+Pj7ETdo7wjsFIZDpfz98PuhHaUBMoKjVtoA5n/+B5Mq9BfBe4Qf57nQEHguzmFAs5Sao9tOxIbPda0p/osu5ly8ebYToqemCIekSX3HzHTSLy4eXjaIreRHlLIPmEMa65RC+Dngqs/+qwAmvtFdymK5wVmbWGFMjIuF9/U=
  app: unai-emery
  on:
    repo: devawal5/BasicWebApp
