language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: KPSNcMuLob7gmr7TgYA6jQ4wwdy/bcNXJPeSJF7I+O0y1si+60EhnGE7vOPa1rYUaXiMAMEBggetw4OvxjkBDSmqV71mvjam0ojO0IdUHKGkWt6eC2UqNLji3txPxc/hczGhlzdYLujm9EcJNrqpj1U+myqbKnSOz+L1rQ0PPDMkkHT3uwE3nLpmpthTdFb2ne4Rs9p3YeHdNJ44BuLCnSwZbYjCY+ANPmo3tnrItMLSOzynFK9e4vHvO+YtYJeKtqlMgkdOKuYAbuRyf+hEhEL+mXN6MSB8vA2ecQieVI9WGnZXeSW8Sd4LB0jMTPqMsc+9dquI7DA4ozilWQVn8SUuryaTumFzTIoYilbBIqYMrm/8vPH/SWPv9N9lkPyS/OM6WbCGQjUWBzZ+8fab+ZIz0YSpzYCeloLCY7pCP1axnx4Pf9UZtm2bxUOFX0JuH+cuHYXQ43kP3FKzhPo0i3MSQNQwwy90xhb+0HcrtpMR4idgf995ZBjlhq4MGPXbZHkVuXFL0ToWkaTbUr5exFif2tT+BxypA4PM+1iFwsxYlaplBx7IRC4ojp7vhDvqQritvJKmCxHSEHYp04KdrEQU9FGZF8xRNRlB+f2h5Lq9dzIwrZO5aK+y17v5K6PYFfwlJvxs18N2Naui9Q6zdJW3vqa4rsGq+3ZVeRJv16Y=
  app: unai-emery
