language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: PkNR9Skf1Zc/1+9HH0lkOawXTYjOEWfw7M8oMYb7VNkwOeZjLMalGHFcup2PLOHZVevSXHdQQJpl2ESVKRuqdVZ9jb9kVpnVcpZVBuIvp0GMNR4ojSMVymyTBNMBI3uiBCKkpOiCtziC/sjtDLnsYnMkaP92Hc+hqFFygldJjiD7OFpkHyNGndet++FL4QqSdBA4hWu1aFZ6hhkmgdoWeRVSCHwYwAd8JgzApsvYdhtBR/J+ZxDu8ILo8CQeaH9+ZIYYH85Y04KBmC1kU0Va2WU7D4gDVP4zVLwrDwZlyY8RDP01h/YP+MNiVp+okrNVGbjimceSEQ2uHskBBataqCBlVtWaRaV4WorCV35oGp1DOs76xm+HMwW9BygeYIfhiHcEmbphOEvKvL3lAY4+sf0YbCf6GJ0z33bvCXhdoyvC36Xzxg/VJq90T3EdATBjgVONjI3jxG5pWO0eLtbyKeUkP08RjSMH1/08fLY81K3nd61UsyDoLZdx0KDJ1Pg//KhzoXEHGWLm8E20Tcip5CoEP0Vl0rWvzC3mOn8JkU6OWArg5RLdGOeZxhmLdKC4XBCspvcZ10ts/SckZfpZitkZUJFGQTAiiBNmF3BXmjYfE3TUfORpOzNMGTj0tHVbd1wdKiFsEfp10STj1y00cPbUejVUXRXLzpdWQw8w7aw=
  app: unai-emery
  on:
    repo: devawal5/BasicWebApp
