language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: TabIiV22HnIS+zNHkUoOE5em0k2LBx6X7GMgoWrYFFIz/0/QzJPj1hcZDcRaAspJHBdQdFhMmN/Q4RfKoWpaQ6LQqzqnHvH5Miv3M/rdRmaUgqBIr8ImHYGhNMyw/68h7XWPf35g3EGguu/j7z6ebQm7oreUz3kYx07wjoI8ScZ1y5OvHktpIrLIYoUewWQsuDUW0eYy4s7Wf60Nv4lwEP2Ud//BJfYHFXnLOM+XHKU6+FVECfdNXYj+ZfC4StJrWI2DyvTonO2zbEWHsxej4mhKFsgN+GEnjtR6b1EbjSGEO2zkCtQlnh/YVWvIa62gzkQixlFMv4UH5ef0dXHIX7cuOykZHQO9SeB+5xd0eXoMimuwcPxqSMUH5jIyxMsabqrDXlxybYfhJKQdy1Dmxsncd8M9UEuph6/SAblKRrBQCa33vWy+IvsrJpHoIpSh9ATLZTUcjnbeuaygpL4pC/VCORNiExHeEBoasumpIJiHT1dNpImI+6sEzqTLhh5U0gvn0E06NDUBP53XRcCJzb/htzk2anzJMuVbgxFZZvBVM+i1Pp0Q0VlMhOan0BcgnPI5FXTJkppTQ3klo4SCqdAl9IkXe49AGtS03vKoHcggFn9QL/yMtOOmZkxwNCKca8eOmkhgv9hOLma9q2G/01CYfNRhaMQuSaNKa4TM4f8=
  app: unai-emery
  on:
    repo: devawal5/BasicWebApp
