language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: YVxlBFRU3nB7UMb5ZQBwcia5H4mUkWokEcRL0GiHwi4L/gJNo9HuzsDjYiDLxsPvuahs5DoNmxwt3d2dc88P6tMUU0uLf3r1/ex5uZ3F0MxQqePRkVdNBiiWGqIebNj7/Z7KiSOZ/8ZDxZpjLpY4i1XvOIV3CzPpWxdIq7MvQ/xis5XJY9xeSKNHYuRNmQulz2gxMRokEQ0PgxwMABnFaRBOLBxWLzkkWdtT3S+tT5THqpGOftrpNXLRyYIaHj/9TJYerWtnCLgaonJDYjp5DMEAGBGz0GVRUtcgCH1194aQFuGc53ZlQrm1B7tpHlWVtEAGzEZOTo88kC+WTf+7wkTflgUwNrP33RWU1YU5pCm4E77s1t3tTxvuvkQg9Mn2Nrhw8VvxSXIG6RcZquArzvKvLyXH/kDwFgv/azYwXCuTp9MYTuskeVJL1DTtUjbtDTCsPn50Jeu01i7z3woGcN7PGFF/JJQufahhs5yuHWNRCs3xdjqZM3RhxM67pe3uSb78CTqIlp1bxkxxSO3MJpK360mxwpwVK3vhCnIUPR3epSz5Z3jiO3Ed1tf6qkoCjx5L2aCg1JAMgcksL7gnK48uDlIYC1SClUbqqh0zdEqaMD/8+HqD42gwKiyvty0gKjo8eU0hCs1H0C4btyv0z5tTNWpTBK09p6WTLpiO84c=
  app: unai-emery
