language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: T7farOGKvjIo0NxZZBpDevqvSRBz9fMv6BIGjcefwzsPEK8hku0qS9hb8Y3U8e5JXtHXkvsJWjLGB6XAe/cRAazclUiUPu150z+K/f7nBe8esBtMhwWTzTs2md/fEfMwNxJYHSv2O2DBWi2TirFzYk+ELY3UOX5pXV8QqMmeSCLPfYKm1aDecJT8k5/rE99NN7DsGISG7KVRO/MlFjKlHBtsqactILhwmPM6fmur1XLRJs6cowa13t674K6XG4tPqpPdU2MNDImgButRUgNVNSG3TK+oYZk7WYZTR9S2x4qYn0ZpuF++HMdqLOvrOrIEXtOuwTBlvRZn8WGBsoV9ibvqxE5QfekBna2E0RtD4RR/jdw7595yKqGa0I/iA+p1BmbkVkstBrGf8cfzn7uevvznDxNO2GIAjYaqbubpTmMN+yM2xrrMUBZ8BsOdYQdb6SPNDRuff8IW3lC4O3la5mWiTZ88FnI3PpTR7S9AUUVakHY4CK4B/rZHEOFFId+Jnn8oazh36c9QVaJg2N8G83OgBCIPzeFTwvQf8juWJnjzEkLa2Y2HZA23BKcZxHRfdwc6v/9PQL3tKD9iehVeRatpMoAcXqQt7qbyZGZwrLRvG80Dkds9fDqEBKekhUEZPaFJOlO7W4L9c+59bSd91K1oayfImfwJM2ba3LDerdA=
  app: unai-emery
